spring:
  application.name: "user_service_app"
  profiles.active: "development"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
      discovery:
        enabled: true
        service-id: "configserver"

logging:
  level.root: "DEBUG"