openapi: 3.0.2
info:
  title: Tweet_Service
  description: "API related to tweets in twitter clone"
  contact:
    email: sanchitbansal10@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about Reflectoring
  url: https://sanchitbansal.com
tags:
  - name: tweet
    description: Operations about tweet
paths:
  /tweet/post:
    post:
      tags:
        - tweet
      summary: Post tweet
      description: Post tweet functionality
      operationId: postTweet
      requestBody:
        description: Created Tweet object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Tweet'
        required: true
      responses:
        default:
          description: successful operation
          content: {}
      x-codegen-request-body-name: body

  /tweet/{tweetId}:
    get:
      summary: Get a tweet by ID
      parameters:
        - in: path
          name: tweetId
          schema:
            type: integer
          required: true
          description: Numeric ID of the tweet to get
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
        '404':
          description: tweet not found
          content: {}
components:
  schemas:
    Tweet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        user_id:
          type: string
        total_likes:
          type: integer
          format: int64
        total_comments:
          type: integer
          format: int64
  securitySchemes:
    reflectoring_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://reflectoring.swagger.io/oauth/dialog
          scopes:
            write:users: modify users
            read:users: read users
    api_key:
      type: apiKey
      name: api_key
      in: header